# $Id: Makefile 5901 2014-02-20 07:45:05Z dingjun $
#
# Usrmgtmodule Makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=usrmgt.so
LIBS=

include ../../Makefile.modules
